# This file contains values from Cookiecutter

default_context:
  project_name: "spacy-cleaner"
  project_description: "Easily clean text with spaCy!"
  organization: "spacy-cleaner"
  license: "MIT"
  minimal_python_version: 3.7
  github_name: "spacy_cleaner"
  email: "hallcellan@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
