name: Build Poetry

description: 'Build Poetry'

runs:
  using: 'composite'

  steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: '${{ matrix.python-version }}'

    - name: Get full Python version
      id: full-python-version
      run: echo "version=$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")" >> $GITHUB_OUTPUT
      shell: bash

    - name: Bootstrap poetry
      run: curl -sL https://install.python-poetry.org | python - -y
      shell: bash

    - name: Update PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash

    - name: Update PATH
      if: ${{ matrix.os != 'Windows' }}
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash

    - name: Set up cache
      uses: actions/cache@v3
      id: cache
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Ensure cache is healthy
      if: steps.cache.outputs.cache-hit == 'true'
      run: timeout 10s poetry run pip --version || rm -rf .venv
      shell: bash

    - name: Install dependencies
      run: poetry install
      shell: bash
