name: Codecov Workflow

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  code-coverage:
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        os: [ Ubuntu ]
        python-version: [ "3.8" ]
        include:
          - os: Ubuntu
            image: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Python
        uses: ./.github/actions

      - name: Run pytest
        run:  poetry run pytest --cov-report xml --cov=spacy_cleaner tests/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
